name: Update VEX Hub
on:
  schedule:
    - cron: "0 0 * * *" # Every day
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update:
    name: Update VEX Hub
    runs-on: ubuntu-24.04
    env:
      VEXHUB_CRAWLER_COMMIT: "12dbf9a0ad3531a107bf06f618e2308f34b0a5e8"
    steps:
      - name: Check out vexhub repository
        uses: actions/checkout@v4
        with:
          path: vexhub

      - name: Check out vexhub-crawler
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/vexhub-crawler
          ref: ${{ env.VEXHUB_CRAWLER_COMMIT }}
          path: vexhub-crawler

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: vexhub-crawler/go.mod

      - name: Set up git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Build vexhub-crawler
        run: |
          cd vexhub-crawler
          go install .
          cd ..

      - name: Run vexhub-crawler
        run: |
          vexhub-crawler --config ./vexhub-crawler/crawler.yaml --vexhub-dir ./vexhub

      - name: Commit and push changes
        run: |
          cd vexhub
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update VEX documents"
            git push
          else
            echo "No changes to commit"
          fi